version: "3.8"
services:
  flask-app:
    build:
      context: .
      dockerfile: ./dockerfile
    image: flask-app
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    expose:
      - "5000"